In [5]:
#Program to create an array and perform addition of two matrices(using list and NumPy array).
import numpy as np
arr_1=np.array([[1,2,3],[10,11,12]])
arr_2=np.array([[4,6,7],[20,30,10]])
print("Matrix A: ")
print(arr_1)
print("Matrix B: ")
print(arr_2)
print("Addition of the two matrices: ")
print(arr_1+arr_2)

Matrix A: 
[[ 1  2  3]
 [10 11 12]]
Matrix B: 
[[ 4  6  7]
 [20 30 10]]
Addition of the two matrices: 
[[ 5  8 10]
 [30 41 22]]
