In [13]:
#Program to create an array and perform addition of two matrices(using list and NumPy array).
#Create two matruces using nested lists
matrix1=[[1,2,3],[4,5,6]]
matrix2=[[7,8,9],[10,11,12]]
result=[[0,0,0],[0,0,0]]

for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        result[i][j]=matrix1[i][j]+matrix2[i][j]
print("Matrix 1:")
for row in matrix1:
    print(row)

print("\nMatrix 2:")
for row in matrix2:
    print(row)
print("\nSum of Matrix 1 and Matrix 2:")
for row in result:
    print(row)

Matrix 1:
[1, 2, 3]
[4, 5, 6]

Matrix 2:
[7, 8, 9]
[10, 11, 12]

Sum of Matrix 1 and Matrix 2:
[8, 10, 12]
[14, 16, 18]


In [14]:
#Program to create an array and perform addition of two matrices(using list and NumPy array).
import numpy as np
arr_1=np.array([[1,3,5],[10,11,12]])
arr_2=np.array([[5,6,8],[20,30,10]])
print("Matrix A: ")
print(arr_1)
print("Matrix B: ")
print(arr_2)
print("Addition of the two matrices: ")
print(arr_1+arr_2)

Matrix A: 
[[ 1  3  5]
 [10 11 12]]
Matrix B: 
[[ 5  6  8]
 [20 30 10]]
Addition of the two matrices: 
[[ 6  9 13]
 [30 41 22]]
